export const User = {
    account_type: "Listing",
    allow_messaging: true,
    avatar_url: "/user_files/1/businessman-avatar-icon-01-.jpg",
    display_fullname: true,
    email_notifications: false,
    hide_email: false,
    user_address: "3475 E 27th Ave",
    user_bio: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda ullam repellat maiores aperiam debitis iure, repudiandae maxime pariatur nam rerum quasi numquam aliquid illo temporibus amet officiis, veritatis ipsum? Illum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur similique quae tenetur repellat earum voluptate, reiciendis doloribus. Pariatur atque porro sunt autem quod harum soluta necessitatibus tempora hic. Molestias, harum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic molestiae nihil, optio accusantium repellat ex cupiditate commodi similique facere minus maxime explicabo dolorum neque veniam corrupti ipsa debitis. Pariatur, necessitatibus. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus voluptatem, a molestias aperiam obcaecati doloribus harum veritatis suscipit asperiores hic exercitationem molestiae aliquid soluta minima! Laborum placeat saepe dolores! Enim.",
    user_business_name: "RC Web Development",
    user_city: "Vancouver",
    user_city_code: "V5R1P8",
    user_country: "Canada",
    user_education: "BCIT",
    user_email: "rogerchin85@gmail.com",
    user_facebook: "https://www.facebook.com",
    user_firstname: "Roger",
    user_github: "https://github.com/Rc85",
    user_instagram: "https://www.instagram.com",
    user_last_login: "2018-12-10T00:32:16.540Z",
    user_lastname: "Chin",
    user_linkedin: "https://www.linkedin.com",
    user_phone: "604-889-8353",
    user_profile_id: 1,
    user_region: "British Columbia",
    user_setting_id: 1,
    user_title: "Web Developer",
    user_twitter: "https://www.twitter.com",
    user_website: "https://www.rogerchin.me",
    user_worldwide: null,
    username: "roger85"
}