import React from 'react';
import TitledContainer from '../utils/TitledContainer';
import { NavLink } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFileContract } from '@fortawesome/free-solid-svg-icons';

const TermsOfService = props => {
    return(
        <section id='tos' className='main-panel'>
            <TitledContainer title='Terms of Service' icon={<FontAwesomeIcon icon={faFileContract} />} shadow bgColor='info'>
                <h2>Definitions</h2>

                <p><strong>Agreement</strong> - The terms of service is the agreement between you and HireWorld.</p>

                <p><strong>Appeal</strong> - A feature that allow users to appeal the other party's decision when deciding if a job is complete or not.</p>
                
                <p><strong>Boosting</strong> - Creating accounts to promote one's account; Paying other users to promote one's account.</p>

                <p><strong>Content(s)</strong> - Content refers to any text, images, and/or files submitted to the website and made viewable to the public.</p>

                <p><strong>Intangible Property</strong> - Any data produced and/or generated by HireWorld such as and not limited to, stats and medals.</p>

                <p><strong>HireWorld, Our, Us, We</strong> - The website and its owner providing the service.</p>

                <p><strong>Medal(s)</strong> - An intangible item purchased on the website to honor other users.</p>

                <p><strong>Service(s)</strong> - Everything that the website provides and user can engage in such as and not limited to, messaging, reporting, and submitting and modifying content.</p>

                <p><strong>User, You, Your</strong> - Individuals, groups, or organizations who has an account with HireWorld.</p>

                <hr/>

                <h2 id='top' className='mb-3'>Table of Content</h2>

                <div className='mb-1'><a href='#intro'>Introduction</a></div>
                <div className='mb-1'><a href='#changes'>Changes to the Website and Services</a></div>
                <div className='mb-1'><a href='#use'>Your Use of the Service</a></div>
                <div className='mb-1'><a href='#cantdo'>What You Can't Do</a></div>
                <div className='mb-1'><a href='#business'>Conducting Business on HireWorld</a></div>
                <div className='mb-1'><a href='#promotions'>Promotions</a></div>
                <div className='mb-1'><a href='#fees'>Fees</a></div>
                <div className='mb-1'><a href='#purchases'>Payments, Purchases, and Subscriptions</a></div>
                <div className='mb-1'><a href='#refunds'>Refunds, Chargebacks, and Disputes</a></div>
                <div className='mb-1'><a href='#content'>Content</a></div>
                <div className='mb-1'><a href='#licensing'>Licensing and Ownership</a></div>
                <div className='mb-1'><a href='#termination'>Termination</a></div>
                <div className='mb-1'><a href='#indemnity'>Indemnity</a></div>
                <div className='mb-1'><a href='#disclaimer'>Disclaimer</a></div>
                <div className='mb-1'><a href='#liability'>Limitation of Liability</a></div>

                <hr/>

                <h2 id='intro'>Introduction</h2>

                <p>This agreement is written as of December 5, 2018 and applies to your access to our website and use of our services.</p>

                <p>To begin using our service(s), you must agree to all the terms set out in this agreement and you hereby acknowledge that you:</p>

                <ol>
                    <li>Do not possess any mental, physical or emotional conditions that can alter your judgment in making decisions.</li>
                    <li>Understand each and every term entirely, set out in this agreement.</li>
                    <li>You are 18 years or older when agreeing to our terms of service.</li>
                </ol>

                <p>If you do not agree to any of the terms outlined in this agreement, you are prohibited from registering for an account and the use of our services. HireWorld reserves the right to change or modify this agreement, in whole or in part, and prior to doing so, HireWorld will provide a 30 day notice to you regarding that a change or modification has been made.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='changes'>Changes to the Website and Services</h2>

                <p>HireWorld reserves the right to change any or all of HireWorld's website, features, pricing, and services and is not obligated to provide notice. When notice is provided, it means that HireWorld feels the change is worth notifying users and it is entirely out of courtesy and respect of its users. HireWorld will not reimburse and/or compensate in any way if a change is made and users feel they should have been informed.</p>

                <div className='text-right'><a href='#Top'>Top</a></div>

                <hr/>

                <h2 id='use'>Your Use of the Service</h2>

                <p>To begin using our service, you agree to allow us to send you a confirmation email to activate your account. You agree that cookies will be used and stored on your computer for identification purposes. You will be granted access to the service(s) as is, when you activate your account. Each account is restricted to the use of the registered user only. All actions performed on your user account is solely your responsibility. We strongly encourage not share the use of your user account with any other person, group, company and/or organization. If your account is compromised beyond our control and actions have been performed or executed before you realize your account is compromised, we will issue the appropriate response to those actions as if those actions were performed or executed by you and there is no way to appeal our decision(s).</p>

                <p>The use of our service(s) is restricted and not limited to the following:</p>

                <ul>
                    <li>Selling and/or trading of HireWorld accounts with other users.</li>
                    <li>Selling and/or listing services that are related to criminal activities.</li>
                    <li>Selling and/or listing products that are illegal and related to criminal activities.</li>
                    <li>Submitting, uploading, exchanging, transferring and communicating content and information that are illegal and related to criminal activities.</li>
                    <li>Boosting another user account.</li>
                </ul>
                
                <p>HireWorld reserves the right to modify, suspend and/or remove your account at any time with or without notice.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='cantdo'>What You Can't Do</h2>

                <p>HireWorld respects its users and their personal well-being and tries to keep the community an appropriate and mature place to conduct business. HireWorld will not tolerate with behaviors that fall under and not limted to the following:</p>

                <ul>
                    <li>Excessive and unnecessary profanity; we're all adults and can communicate like adults.</li>
                    <li>Harrassments, racism, and personal insults. There is no need for any of those here.</li>
                    <li>Spams of any nature.</li>
                    <li>Defamation of another user without explanation. If you have something bad to say, make it a constructive feedback.</li>
                </ul>

                <p>HireWorld reserves the right to determine and judge whether your actions, choice of words, or any activities related to you and your user account is considered appropriate and can issue disciplinary actions that we feel is justifiable.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='business'>Conducting Business on HireWorld</h2>

                <p>When conducting business on HireWorld, we reserve the right to use any information in circumstances where we need to execute an investigation for fraudelent activities. The information cannot hold a user accountable unless applicable by law. The information will also be used to assist our administrator(s) in deciding the outcome of an appeal request. HireWorld reserves the right to reverse any intangible property gained and/or loss through the process related to the appealing case.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <h2 id='promotions'>Promotions</h2>

                <p>HireWorld is not obligated to state and/or indicate the end date of a promotion. We have every right to terminate a promotion at any time and a notice may or may not be provided to you.</p>

                <p>Promotional codes have no value and are not to be sold, traded, and/or profited in any way to the user distributing it.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='fees'>Fees</h2>

                <p>When using services at HireWorld, a fee may be charged. In the event where you choose to use a service that requires a fee, we will clearly outline the details of the fee before you agree to use the service. HireWorld reserves the right to refuse any service for any reason we feel may put us in jeopardy with the law of any city, region, country, or jurisdiction. In such case, we will fully refund the fee and as a result of such case, we may flag your account with suspicious activity and may or may not continue service(s) to you ongoing forward.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='purchases'>Payments, Purchases, and Subscriptions</h2>

                <p>By adding a payment, making purchases and/or subscribing to a recurring payment plan at HireWorld, you hereby agree that the information provided by you upon making adding payment, making purchases or subscribing to a plan, will be sent and stored on <a href='https://stripe.com'>Stripe</a>. Furthermore, you acknowledge that you have read, understood, and agreed to <a href='https://stripe.com/privacy'>Stripe's Privacy Policy</a>.</p>

                <p>You have all the rights to cancel your subscription at any time and the service will still be available to you for the remaining time that you paid for.</p>

                <p>If you are found guilty of violating any terms in this agreement, HireWorld reserves the right to:</p>

                <ol>
                    <li>Terminate any service to you immediately without refunds</li>
                    <li>Refuse any purchases and services to you</li>
                    <li>Discontinue any services ongoing forward</li>
                </ol>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='refunds'>Refunds, Chargebacks, and Disputes</h2>

                <p>You agree that all payments processed and transferred are final and there will be no refunds from the HireWorld and/or the user you transfer the funds to unless otherwise applicable by law.</p>

                <p>We take chargebacks seriously and if such case occurs, we may or may not continue service to you ongoing forward depending on the nature of the chargeback. We fully understand under circumstances where financial information are compromised, that a chargeback can happen. If this is the case, you can proivde us with information and proof of the incident for us to decide to continue service to you.</p>

                <p>You have all the rights to dispute a charge or a transfer of funds with HireWorld at any time for whatever reason you feel the charge or transfer of funds was unreasonable, accidental, or in any nature that was out of your control such as and not limited to, a compromised user account.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='content'>Content</h2>

                <p>The most important thing at HireWorld is our users and our system. All we ask for when using our service is respect other users and respect our system that provides this service to you. Content being submitted and/or uploaded by you must abide by the following:</p>

                <ul>
                    <li>Content must not contain nudity and/or pornographic visuals.</li>
                    <li>Content must not contain any malicious software or scripts.</li>
                    <li>Content must not contain extreme profanity.</li>
                    <li>Content must not any nature of harrassment, racism, sexism, and/or personal insult to the user, the user's race, the user's culture, the user's business, and/or the user's gender.</li>
                    <li>Content must not contain spam of any kind.</li>
                    <li>Content must not be direct defamation to another user's business.</li>
                    <li>Content must not be infringed, copied, plagerized, counterfeited, and stolen from its original source.</li>
                </ul>

                <p>HireWorld assumes all copyrighted content and trademark submitted and/or uploaded to the website has been permitted by the original owner and/or you are the sole owner of the material. If any action is taken by the original owner, the action is taken against you and you agree to be fully liable and will take full responsibility in handling the matter. Should the matter go unresolved, HireWorld reserve the rights to remove the content from our website and/or terminating your account if it deems necessary.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='licensing'>Licensing and Ownership</h2>

                <p>The user account and account only, in which you register your email with is a limited, revocable, non-exclusive, non-assignable license to use on HireWorld and it is entirely owned by HireWorld. Unlicensed use of our service is prohibited and unauthorized. You agree to not sell, trade, or transfer the account in any way, shape, or form.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='termination'>Termination</h2>

                <p>You have all the rights to terminate your agreement with HireWorld at any time by discontinuing the use of our service. Terminating your agreement does not mean that the information related to your user account will be deleted. Please refer to our <NavLink to='/privacy'>privacy policy</NavLink> in regards to user's data.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='indemnity'>Indemnity</h2>

                <p>Except to the extent prohibited by law, you agree to defend, indemnify, and hold us, our licensors, our third party service providers and our officers, employees, licensors, and agents harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Services, (b) your violation of these Terms, (c) your violation of applicable laws or regulations, or (d) Your Content. We reserve the right to control the defense of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='disclaimer'>Disclaimer</h2>

                <p>OUR SERVICE IS PROVIDED "AS IS" AND ON AN "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. YOU AGREE TO NOT RELY ON THE SERVICE, THE SITE, THE CONTINUATION OF THE SITE, AND INFORMATION ON THE SITE TO CONTINUE CONDUCTING YOUR BUSINESS. WE DO NOT WARRANT THAT ALL INFORMATION AVAILABLE ON THE SITE IS COMPLETELY GENUINE, LEGIMATE, AND SAFE. HIREWORLD DOES NOT WARRANT THAT THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, UP TO DATE, AND ERROR FREE. HIREWORLD DOES NOT CONTROL, ENDORSE, OR TAKE RESPONSIBILITY OF THE CONTENT AVAILALBLE ON, DISPLAYED ON, DOWNLOADED FROM, AND LINKED TO THE SERVICE. HIREWORLD DOES NOT WARRANT THAT CONTENTS DOWNLOADED, OBTAINED, PURCHASED, OR PRODUCED FROM HIREWORLD ARE FREE OF HARMFUL SCRIPTS AND/OR SOFTWARE. HIREWORLD DOES NOT CONTROL, ENDORSE, ENCOURAGE, AND TAKE RESPONSIBILITY OF USERS' ACTIONS ON HOW THEY CHOOSE TO CONDUCT THEIR BUSINESS. HIREWORLD DOES NOT WARRANT THAT ALL APPEALS, DECISIONS, AND DISPUTES ARE ACCURATE AND DOES NOT WARRANT THAT ALL APPEALS, DECISIONS, AND DISPUTES WILL FAVOR THE USERS.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='liability'>Limitation of Liability</h2>

                <p>HireWorld, its employees, officers, directors, and agents will not be liable for any direct, indirect, incidental, consequential, special, and punitive losses or damages to you and your business whatsoever resulting from a) any errors, mistakes, and/or inaccuracies of the content; b) Property or personal injury of any nature resulting from the use and access to the services; c) Any unauthorized access to or use of our servers and/or any personal and financial information stored therein; d) Your use of any content downloaded, posted, exchanged, transferred, or otherwise made available via the services. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction.</p>

                <p>You specifically acknowledge that HireWorld shall not be liable for content or the defamatory, offensive, or illegal conduct of any third party and that the risk of harm or damage from the foregoing rests entirely with you.</p>

                <p>The service is controlled and offered by HireWorld from its facility in Canada. HireWorld makes no representations that the service is appropriate or available for use in other locations. Those who access or use the service from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>

                <div className='text-right'><a href='#top'>Top</a></div>
            </TitledContainer>
        </section>
    )
}

export default TermsOfService;