import React from 'react';
import TitledContainer from '../utils/TitledContainer';
import { NavLink } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFileContract } from '@fortawesome/free-solid-svg-icons';

const TermsOfService = props => {
    return(
        <section id='tos' className='main-panel'>
            <TitledContainer title='Terms of Service' icon={<FontAwesomeIcon icon={faFileContract} />} shadow bgColor='info'>
                <h2>Definitions</h2>

                <p><strong>Agreement</strong> - The terms of service is the agreement between you and Hire World.</p>

                <p><strong>Appeal</strong> - A feature that allow users to appeal the other party's decision when deciding if a job is complete or not.</p>
                
                <p><strong>Boosting</strong> - Creating accounts to promote one's account; Paying other users to promote one's account.</p>

                <p><strong>Content(s)</strong> - Content refers to any text, images, and/or files submitted to the website and made viewable to the public.</p>

                <p><strong>Intangible Property</strong> - Any data produced and/or generated by Hire World such as and not limited to, stats and medals.</p>

                <p><strong>Hire World, Our, Us, We</strong> - The website and its owner providing the service.</p>

                <p><strong>Medal(s)</strong> - An intangible item purchased on the website to honor other users.</p>

                <p><strong>Service(s)</strong> - Everything that the website provides and user can engage in such as and not limited to, messaging, reporting, and submitting and modifying content.</p>

                <p><strong>User, You, Your</strong> - Individuals, groups, or organizations who has an account with Hire World.</p>

                <hr/>

                <h2 id='top' className='mb-3'>Table of Content</h2>

                <div className='mb-1'><a href='#intro'>Introduction</a></div>
                <div className='mb-1'><a href='#changes'>Changes to the Website and Services</a></div>
                <div className='mb-1'><a href='#use'>Your Use of the Service</a></div>
                <div className='mb-1'><a href='#cantdo'>What You Can't Do</a></div>
                <div className='mb-1'><a href='#promotions'>Promotions</a></div>
                <div className='mb-1'><a href='#fees'>Fees</a></div>
                <div className='mb-1'><a href='#purchases'>Payments, Purchases, and Subscriptions</a></div>
                <div className='mb-1'><a href='#refunds'>Refunds, Chargebacks, and Disputes</a></div>
                <div className='mb-1'><a href='#content'>Content</a></div>
                <div className='mb-1'><a href='#licensing'>Licensing and Ownership</a></div>
                <div className='mb-1'><a href='#termination'>Termination</a></div>
                <div className='mb-1'><a href='#indemnity'>Indemnity</a></div>
                <div className='mb-1'><a href='#disclaimer'>Disclaimer</a></div>
                <div className='mb-1'><a href='#liability'>Limitation of Liability</a></div>

                <hr/>

                <h2 id='intro'>Introduction</h2>

                <p>This agreement is written as of December 5, 2018 and applies to your access to our website and use of our services.</p>

                <p>To begin using our service(s), you must agree to all the terms set out in this agreement and you hereby acknowledge that you:</p>

                <ol>
                    <li>Do not possess any mental, physical or emotional conditions that can alter your judgment in making decisions.</li>
                    <li>Understand each and every term entirely, set out in this agreement.</li>
                    <li>You are 18 years or older when agreeing to our terms of service.</li>
                </ol>

                <p>If you do not agree to any of the terms outlined in this agreement, you are prohibited from registering for an account and the use of our services. Hire World reserves the right to change or modify this agreement, in whole or in part, and prior to doing so, Hire World will provide a 30 day notice to you regarding that a change or modification has been made.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='changes'>Changes to the Website and Services</h2>

                <p>Hire World reserves the right to change any or all of Hire World's website, features, pricing, and services and is not obligated to provide notice. When notice is provided, it means that Hire World feels the change is worth notifying users and it is entirely out of courtesy and respect of its users. Hire World will not reimburse and/or compensate in any way if a change is made and users feel they should have been informed.</p>

                <div className='text-right'><a href='#Top'>Top</a></div>

                <hr/>

                <h2 id='use'>Your Use of the Service</h2>

                <p>To begin using our service, you agree to allow us to send you a confirmation email to activate your account. You agree that cookies will be used and stored on your computer for identification purposes. You will be granted access to the service(s) as is, when you activate your account. Each account is restricted to the use of the registered user only. All actions performed on your user account is solely your responsibility. If your account is compromised beyond our control and actions have been performed or executed before you realize your account is compromised, we will issue the appropriate response to those actions as if those actions were performed or executed by you and there is no way to appeal our decision(s).</p>

                <p>The use of our service(s) is restricted and not limited to the following:</p>

                <ul>
                    <li>Selling and/or trading of Hire World accounts with other users.</li>
                    <li>Selling and/or listing services that are related to criminal activities.</li>
                    <li>Selling and/or listing products that are illegal and related to criminal activities.</li>
                    <li>Submitting, uploading, exchanging, transferring and communicating content and information that are illegal and related to criminal activities.</li>
                    <li>Boosting another user account.</li>
                </ul>
                
                <p>Hire World reserves the right to modify, suspend and/or remove your account at any time with or without notice.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='business'>Doing Business on Hire World</h2>

                <p>As a service provider, when creating and submitting milestones to the client, the milestones and conditions contained in each milestones are agreements between you and the client that any tasks and/or deliverable must satisfy the terms set out in the conditions and any terms in the job description. You are obligated to complete each conditions and milestones until the job reach its completion stage. Should any issue arise regarding that the deliverable does not satisfy the agreed terms, you have the right to request partial payments from the client.</p>

                <p>As a client, when sending a job proposal to a service provider, the job description acts as agreeable terms between you and the service provider. Should there be any disagreement after the job has begun, you agree to establishment an agreement with the service provider to the best of your ability. You have all the rights to file a dispute for Hire World to interfere with the business or close the job and stop any further business with the service provider.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='cantdo'>What You Can't Do</h2>

                <p>Hire World respects its users and their personal well-being and will to maintain the community to be an appropriate and mature place to conduct business. Hire World will not tolerate with behaviors that fall under and not limted to the following:</p>

                <ul>
                    <li>Excessive and unnecessary profanity.</li>
                    <li>Harrassments, racism, and personal insults.</li>
                    <li>Spams of any nature.</li>
                    <li>Intent to defame another user to negatively impact the user's business.</li>
                </ul>

                <p>Hire World reserves the right to determine and judge whether your actions, choice of words, or any activities perform, related, and/or submitted by you and your user account are considered appropriate and may issue disciplinary actions that we feel is justifiable.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='promotions'>Promotions</h2>

                <p>Hire World is not obligated to state, announce, notify users, or remind users the end date of a promotion. We have every right to terminate a promotion at any time and a notice may or may not be provided to you.</p>

                <p>Promotional codes have no value and are not to be sold, traded, and/or profited in any way to the user distributing it.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='fees'>Fees</h2>

                <p>When using services at Hire World, a fee may be charged. Hire World reserves the right to refuse any service for any reason we feel that your use of our service may put us in jeopardy with the law of any city, region, country, or jurisdiction. In such case, we may flag your account with fraudulent activity and may or may not continue service(s) to you ongoing forward.</p>

                <p>When using our service to handle payments between you and another party, you hereby acknowledge that if no payments are made to the other party, the fee to transfer funds between you and our platform will not be refunded.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='purchases'>Payments, Purchases, and Subscriptions</h2>

                <p>By adding a payment, making a purchase and/or subscribing to a recurring payment plan at Hire World, you hereby agree that the information provided by you upon adding the payment, making the purchases or subscribing to a plan, will be sent and stored on <a href='https://stripe.com'>Stripe</a>. Furthermore, you acknowledge that you have read, understood, and agreed to <a href='https://stripe.com/privacy'>Stripe's Privacy Policy</a>.</p>

                <p>You have all the rights to cancel your subscription at any time and the service will still be available to you for the remaining time that you paid for.</p>

                <p>If you are found violating any terms in this agreement, Hire World reserves the right to:</p>

                <ol>
                    <li>Terminate any service to you immediately without refunds</li>
                    <li>Refuse any purchases and services to you</li>
                    <li>Discontinue any services ongoing forward</li>
                </ol>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='refunds'>Refunds, Chargebacks, and Filing a Case</h2>

                <p>You agree that all payments made to subscribe to a monthly plan is not refunded unless applicable by law.</p>

                <p>If no payments are made to the other party with the funds that was transferred to Hire World, you will receive the refund minus any Stripe charge fee and your portion of the application fee. See <a href='https://stripe.com/pricing'>Stripe pricing</a> and <NavLink to='/pricing'>our pricing</NavLink> for more details.</p>

                <p>If partial payment is made to the other party with the funds that was transferred to Hire World, you will receive the remainder of the funds minus the amount you paid, any Stripe fee, and your portion of the application fee.</p>

                <p>We take chargebacks seriously and if such case occurs, we may or may not continue service to you ongoing forward depending on the nature of the chargeback. We fully understand under circumstances where financial information can be compromised and as a result of that, a chargeback can happen. If this is the case, you can proivde us with information and proof of the incident for us to investigate and decide to continue service to you.</p>
                
                <p>Cases can be filed in events where any deliverable does not satisfy agreed terms. In contrast, cases can be filed if no payments are made after a deliverable is delivered. In the event a case is opened between you and the other party, you agree to communicate with us effectively, promptly, and submit any evidence that is relevant to the case to help us reach a decision. You agree upon our request, to submit any files, assets, items (tangible or intangible), properties, that you may have sent or received from the job to us to help us reach a decision.</p>

                <p>If you refuse to communicate with us regarding a case, you agree to give us permission to forfeit any payments held on our platform.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='content'>Content</h2>

                <p>Content being submitted and/or uploaded by you must abide by the following:</p>

                <ul>
                    <li>Content must not contain nudity and/or pornographic visuals.</li>
                    <li>Content must not contain any malicious software or scripts.</li>
                    <li>Content must not contain extreme profanity.</li>
                    <li>Content must not be and contain any nature of harrassment, racism, sexism, and/or personal insult to the user, the user's race, the user's culture, the user's business, and/or the user's gender.</li>
                    <li>Content must not contain spam of any kind.</li>
                    <li>Content must not be direct defamation to another user's business.</li>
                    <li>Content must not be infringed, copied, plagerized, counterfeited, and stolen from its original source.</li>
                </ul>

                <p>Hire World assumes all copyrighted content and trademark submitted and/or uploaded to the website has been permitted by the original owner, licensed by you, and/or you are the sole owner of the content. If any action is taken by the original owner, the action is taken against you and you agree to be fully liable and will take full responsibility in handling the matter. Should the matter go unresolved, Hire World reserve the rights to remove the content from our website and/or terminating your account if it deems necessary.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='licensing'>Licensing and Ownership</h2>

                <p>The user account and account only, in which you register your email with is a limited, revocable, non-exclusive, non-assignable license to use on Hire World and it is entirely owned by Hire World. Unlicensed use of our service is prohibited and unauthorized. You agree to not sell, trade, or transfer the account in any way, shape, or form.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='termination'>Termination</h2>

                <p>You have all the rights to terminate your agreement with Hire World at any time by discontinuing the use of our service. Terminating your agreement does not mean that the information related to your user account will be deleted. Please refer to our <NavLink to='/privacy'>privacy policy</NavLink> in regards to user's data.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='indemnity'>Indemnity</h2>

                <p>Except to the extent prohibited by law, you agree to defend, indemnify, and hold us, our licensors, our third party service providers and our officers, employees, licensors, and agents harmless, including costs and attorneys’ fees, from any claim or demand made by any third party due to or arising out of (a) your use of the Services, (b) your violation of these Terms, (c) your violation of applicable laws or regulations, or (d) Your Content. We reserve the right to control the defense of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='disclaimer'>Disclaimer</h2>

                <p>OUR SERVICE IS PROVIDED "AS IS" AND ON AN "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. YOU AGREE TO NOT RELY ON THE SERVICE, THE SITE, THE CONTINUATION OF THE SITE, AND INFORMATION ON THE SITE TO CONTINUE CONDUCTING YOUR BUSINESS. WE DO NOT WARRANT THAT ALL INFORMATION AVAILABLE ON THE SITE IS COMPLETELY GENUINE, LEGIMATE, AND SAFE. Hire World DOES NOT WARRANT THAT THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, UP TO DATE, AND ERROR FREE. Hire World DOES NOT CONTROL, ENDORSE, OR TAKE RESPONSIBILITY OF THE CONTENT AVAILALBLE ON, DISPLAYED ON, DOWNLOADED FROM, AND LINKED TO THE SERVICE. Hire World DOES NOT WARRANT THAT CONTENTS DOWNLOADED, OBTAINED, PURCHASED, OR PRODUCED FROM Hire World ARE FREE OF HARMFUL SCRIPTS AND/OR SOFTWARE. Hire World DOES NOT CONTROL, ENDORSE, ENCOURAGE, AND TAKE RESPONSIBILITY OF USERS' ACTIONS ON HOW THEY CHOOSE TO CONDUCT THEIR BUSINESS. Hire World DOES NOT WARRANT THAT ALL APPEALS, DECISIONS, AND DISPUTES ARE ACCURATE AND DOES NOT WARRANT THAT ALL APPEALS, DECISIONS, AND DISPUTES WILL FAVOR THE USERS.</p>

                <div className='text-right'><a href='#top'>Top</a></div>

                <hr/>

                <h2 id='liability'>Limitation of Liability</h2>

                <p>Hire World, its employees, officers, directors, and agents will not be liable for any direct, indirect, incidental, consequential, special, and punitive losses or damages to you and your business whatsoever resulting from a) any errors, mistakes, and/or inaccuracies of the content; b) Property or personal injury of any nature resulting from the use and access to the services; c) Any unauthorized access to or use of our servers and/or any personal and financial information stored therein; d) Your use of any content downloaded, posted, exchanged, transferred, or otherwise made available via the services. The foregoing limitation of liability shall apply to the fullest extent permitted by law in the applicable jurisdiction.</p>

                <p>You specifically acknowledge that Hire World shall not be liable for content or the defamatory, offensive, or illegal conduct of any third party and that the risk of harm or damage from the foregoing rests entirely with you.</p>

                <p>The service is controlled and offered by Hire World from its facility in Canada. Hire World makes no representations that the service is appropriate or available for use in other locations. Those who access or use the service from other jurisdictions do so at their own volition and are responsible for compliance with local law.</p>

                <div className='text-right'><a href='#top'>Top</a></div>
            </TitledContainer>
        </section>
    )
}

export default TermsOfService;