module.exports = {
    usernameCheck: /^[a-zA-Z0-9_-]{5,25}$/,
    passwordCheck: /^.{8,20}$/,
    emailCheck: /^[a-zA-Z0-9_\-]+(\.{1}[a-zA-Z0-9_\-]*){0,2}@{1}[a-zA-Z0-9_\-]+\.([a-zA-Z0-9_\-]*\.{1}){0,2}[a-zA-Z0-9_\-]{2,}$/,
    nameCheck: /^[a-zA-Z]{1,40}$/,
    fullNameCheck: /^[a-zA-Z]{1,}\s[a-zA-Z]{1,}$/,
    blankCheck: /^\s*$/,
    titleCheck: /^[a-zA-Z0-9!@#$%^&*()_+-='";:[\].,\/?\\~`\s]{3,255}$/,
    priceCheck: /^[0-9]*.?[0-9]{0,2}$/,
    businessNameCheck: /^(\w|\d|\s(?!\s)|,|\.|\/|\?|;|'|\[|\]|!|@|#|\$|%|\^|&|\*|\(|\)|_|\+|-|=|{|}|:|"){3,40}$/,
    addressCheck: /^(\w|\d|\s(?!\s)|,|\.|\/|@|#|&|\(|\)|\+|-|:){1,300}$/,
    cityCodeCheck: /^([0-9]{1,5}|[a-zA-Z]{1}[0-9]{1}[a-zA-Z]{1}(\s)?[0-9]{1}[a-zA-Z]{1}[0-9]{1})$/,
    phoneCheck: /^(\+1)?(\s)?([0-9]{1,15}|(\()?[0-9]{3}(\))?(\s|\-)?([0-9]{7,12}|[0-9]{3}(\s|\-)?[0-9]{4,9}))$/,
    locationCheck: /^[a-zA-Z0-9À-ž,'().\-\s\u2011]{1,}$/,
    urlCheck: /^(http:\/\/|https:\/\/|\/\/)?(www\.)?[a-zA-Z0-9\-]*\.[a-zA-Z]{0,5}([a-zA-Z0-9\-\/]*)/,
    userTitleCheck: /^[a-zA-Z0-9À-ž,'().\-\s]{3,30}$/,
    searchUserTitleCheck: /^[a-zA-Z0-9À-ž,'().\-\s]{1,}$/,
    dobYearCheck: /^(1|2){1}[0-9]{3}$/,
    currencyCheck: /^[a-zA-Z]{3}$/,
    integerCheck: /^[0-9]*$/,
    httpCheck: /^(http:\/\/|https:\/\/){1}/
}